spring:
  data:
    mongodb:
#     authentication-database:
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
      database: course
      port: 27017
      host: localhost
  application:
    name: course-service
server:
  port: 8081
